version: '3.10'

services:
  backend:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      - ./RecipeAPI
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
