version: '3.10'

services:

  backend:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./RecipeAPI
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env


volumes:
  postgres_data: